# Site settings
title: Shubham Sachdeva
description: 'Working at Amazon as Sr.Sde (L6) in Alexa'
url: 'https://magiclko.github.io/'
baseurl: ''
profilepic: '/images/shubham.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'ba1eb4a3d2.js'

author:
  name: 'Shubham Sachdeva'
  email: shubham.itsme@icloud.com
  twitter_username: shubhamo_O
#  facebook_username: es
  github_username:  magiclko
  linkedin_username:  shubhamsachdeva
#  meetup_name: Az

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
